name: CommandSigns
main: org.zonedabone.commandsigns.CommandSigns
authors: [zonedabone, HansAnderson]
version: 1.7.3
description: >
             Add commands to signs.
depend: [Vault]
soft-depend: [TriggerCmds]
dev-url: http://dev.bukkit.org/server-mods/command-signs/
commands:
  commandsigns:
    aliases: [cs, cmds, cmdsigns]
    description: CommandSigns commands.
    usage: |
        /commandsigns line<number> - Add a line to your CommandSign clipboard. Right click a sign to activate.
        /commandsigns read - Right click a sign to read the CommandSign text.
        /commandsigns copy - Copy a CommandSigns to your clipboard.
        /commandsigns remove - Right click a sign to remove a CommandSign.
        /commandsigns clear - Clear your CommandSign clipboard.
permissions:
    commandsigns.*:
        description: Gives access to all CommandSigns commands
        children:
            commandsigns.create.*: true
            commandsigns.remove: true
            commandsigns.use.*: true
            commandsigns.group.*: true
            commandsigns.update: true
            commandsigns.save: true
            commandsigns.reload: true
            commandsigns.edit: true
        default: op
    commandsigns.create.*:
        description: Gives access CommandSigns sign creation commands
        children:
            commandsigns.create.regular: true
            commandsigns.create.super: true
            commandsigns.create.redstone: true
            commandsigns.create.op: true
    commandsigns.save:
        description: Allows saving CommandSigns without reloading
        default: false;
    commandsigns.reload:
        description: Reloads CommandSigns and all configuration
        default: false;
    commandsigns.use.*:
        description: Gives access to CommandSigns sign use
        default: true
        children:
            commandsigns.use.regular: true
            commandsigns.use.super: true
    commandsigns.create.regular:
        description: Allows you to create a regular CommandSign
        default: false
    commandsigns.create.super:
        description: Allows you to create a super CommandSign
        default: false
    commandsigns.create.redstone:
        description: Allows you to create redstone-activated signs
        default: false
    commandisgns.create.op:
        description: Allows you to create op-level CommandSigns
        default: false
    commandsigns.remove:
        description: Allows you to remove a CommandSign
        default: false
    commandsigns.use.regular:
        description: Allows you to use a regular CommandSign
        default: false
    commandsigns.use.super:
        description: Allows you to use a super CommandSign
        default: false
    commandsigns.group.*:
        description: Allows you to use all group commands
        default: false
    commandsigns.updates:
        description: Shows this player CommandSigns updates and allows them to update
        default: false
    commandsigns.edit:
        description: Allows editing of CommandSigns
        default: false