package org.zonedabone.commandsigns;

public enum CommandSignsPlayerState {
	BATCH_ENABLE, BATCH_INSERT, BATCH_READ, BATCH_REDSTONE, BATCH_REMOVE, BATCH_TOGGLE, COPY, EDIT, EDIT_SELECT, ENABLE, INSERT, READ, REDSTONE, REMOVE, TOGGLE;
}
